Repository prgrms-aibe-devcourse/AIBE3-Project1-Team04, pull requests merged in 2025-07, with the labels that each got.

#3 📝 Docs: Update README
  .github/workflows/lint-and-build.yml
  README.md
  app/login/page.tsx
  app/places/[id]/page.tsx
  components/Header.tsx
  next.config.ts
  package-lock.json
  package.json
  tsconfig.json
Labels: 문서작업

#32 Feat/#21 mypage read
  app/mypage/ActivitySummary.tsx
  app/mypage/CompletedPostListTab.tsx
  app/mypage/MyTabs.tsx
  app/mypage/PlaceListTab.tsx
  app/mypage/ProfileHeader.tsx
  app/mypage/WritingPostListTab.tsx
  app/mypage/layout.tsx
  app/mypage/page.tsx
  components/mypage/MyPlaceCard.tsx
  components/mypage/MyPostCard.tsx
  hooks/useMypage.ts
  lib/database.ts
  lib/place.ts
Labels: 기능 추가

#48 ✨ Feat: create-post
  app/posts/create/PostForm.tsx
  consts/index.ts
  hooks/usePost.ts
  types/post.type.ts
Labels: 기능 추가, 완료

#39 Feat/#37 mypage edit
  app/layout.tsx
  app/mypage/PlaceListTab.tsx
  app/mypage/WritingPostListTab.tsx
  app/posts/edit/EditForm.tsx
  app/posts/edit/PlaceList.tsx
  app/posts/edit/PlaceSummary.tsx
  app/posts/edit/PostForm.tsx
  app/posts/edit/PostSection.tsx
  app/posts/edit/page.tsx
  components/modal/MessageModal.tsx
  hooks/useMypage.ts
  hooks/usePostEdit.ts
  lib/database.ts
  stores/MessageModalStore.ts
  types/mypage.type.ts
Labels: 기능 추가

#79 Feat/#68 mypage UI
  app/mypage/MockData.ts
  app/mypage/_tab/CompletedPostListTab.tsx
  app/mypage/_tab/PlaceListTab.tsx
  app/mypage/_tab/WritingPostListTab.tsx
  app/mypage/page.tsx
  components/mypage/MyPlaceCard.tsx
  components/mypage/MyPostCard.tsx
  lib/post.ts
  types/mypage.type.ts
Labels: 기능 추가, 디자인
